### ISSUE TITLE
TODO for custom degree shift of d_r

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#86]
The intended application of this is to use `ext-websocket` to work with other spectral sequences, which may have different degree shifts.

Turns out the previous commit wasn't quite enough:
 - [ ] Implement this for the JS interface as well.
 - [ ] `add_product_differential` currently automatically infers the page from the coordinates, which doesn't work in general.
 - [ ] `assert_eq` in `add_differential` still hard codes the shift
